FROM php:8.4-apache

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
git \
unzip \
zip \
libzip-dev \
libonig-dev \
&& rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure pdo_mysql
RUN docker-php-ext-install \
zip \
pdo \
bcmath \
mbstring \
pdo_mysql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN a2enmod rewrite

COPY . .

RUN composer install

RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' \
    /etc/apache2/sites-available/*.conf

RUN sed -ri -e 's!AllowOverride None!AllowOverride All!g' \
    /etc/apache2/apache2.conf

RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html && \
    chmod -R 775 /var/www/html/storage \
    /var/www/html/bootstrap/cache

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["apache2-foreground"]
